# General Information
ACCOUNTS = ["GCQD5F4QP3AZIBJAIK5LZGCY3TCA65KG3XUF25WQ2BVFVRKLX7277J57","GA67JGLPHZ2S3I2HIFIDNFEB65XS4WNTDCLDABTD4BHBQEXLL3MODDXS"] #
# NETWORK_PASSPHRASE ="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Orion group"
ORG_URL="https://orbitx.online/orion_group"
ORG_DESCRIPTION="Orbit ORBX is a non Anchor-Based Orion Group utility token on the Stellar Blockchain. It is permanently Capped at 100,000,000 total Supply"
ORG_OFFICIAL_EMAIL="official@orbitx.online"
ORG_SUPPORT_EMAIL="support@orbitx.online"
ORG_PHYSICAL_ADDRESS="Cal, Nigeria"
ORG_LOGO="https://orbitx.online/orion_group/assets/orion_group_logo.png"


[[CURRENCIES]]
name="Orbit"
code="ORBX"
issuer="GCQD5F4QP3AZIBJAIK5LZGCY3TCA65KG3XUF25WQ2BVFVRKLX7277J57"
status = "live"
display_decimals="7"
is_asset_anchored=false
desc="Orbit is the utility token of the Orion group ecosystem"
image="https://orbitx.online/assets/orbx-logo.png"

[[PRINCIPALS]]
name="EMINENCE"

















