# General Information
ACCOUNTS = ["GDYTQGDGHRXOIWANOUB4DY6BTKMMWTF5PVJC2KZVT6VFP5TYD7W63XO7","GDTTLA5FN532MH3RSXSEQNWWQ7JLPZEXPUT6SKZGAP2CW6G5MKZD5ZWF"] #
# NETWORK_PASSPHRASE ="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Orion group"
ORG_URL="https://orbxorion.online/orion_group"
ORG_DESCRIPTION=""
ORG_OFFICIAL_EMAIL="official@orbxorion.online"
ORG_SUPPORT_EMAIL="support@orbxorion.online"
ORG_PHYSICAL_ADDRESS="Cal, Nigeria"
ORG_LOGO="https://orbxorion.online/orion_group/assets/orion_group_logo.png"


[[CURRENCIES]]
name="Orbit"
code="ORBX"
issuer="GDYTQGDGHRXOIWANOUB4DY6BTKMMWTF5PVJC2KZVT6VFP5TYD7W63XO7"
status = "live"
display_decimals="7"
is_asset_anchored=false
desc="Orbit ORBX is a non Anchor-Based Orion Group utility token on the Stellar Blockchain. It is permanently Capped at 100,000,000 total Supply"
image="https://orbxorion.online/assets/orbx-logo.png"

[[PRINCIPALS]]
name="EMINENCE"




















