# General Information
ACCOUNTS = ["GCKSI3G65TXQ7KMSEQY4FUHQONZ5YLJIVI5VUYHSV4ILHNQHQSC325UA", "GAJUZ3LR4DLJAUQPZT2MKPUOHVEYH6QZRYZOQXNP3R2VRXUD53PVUVCK"] #
# NETWORK_PASSPHRASE ="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Alnitaknet"
ORG_URL="https://www.alnitaknet.online"
ORG_LOGO="https://drive.google.com/file/d/1HoPD7ovBOKFZ_WvFi89lT1LqXtIMNIyK/view?usp=sharing"
ORG_PHYSICAL_ADDRESS="Calabar,Nigeria"
ORG_OFFICIAL_EMAIL="official@alnitaknet.online"
ORG_SUPPORT_EMAIL="support@alnitaknet.online"
ORG_DESCRIPTION="Alnitak is a non Anchor-Based utility token on Stellar"

[[CURRENCIES]]
TokenName="Alnitak"
code="xALT"
decimals="7"
totalSupply = "100000000"
issuer="GCKSI3G65TXQ7KMSEQY4FUHQONZ5YLJIVI5VUYHSV4ILHNQHQSC325UA"
is_asset_anchored=false
desc="Alnitak is a utility token on Stellar"
image="https://drive.google.com/file/d/1HoPD7ovBOKFZ_WvFi89lT1LqXtIMNIyK/view?usp=sharing"

Token Distribution
distribution.community
 allocation="50%"
  amount="50000000"
  
distribution.team
 allocation="20%"
  amount="20000000"

distribution.partners
allocation="10%"
  amount="10000000"

distribution.reserves
  allocation="20%"
  amount="20000000"

[security]
  multiSignatureWallets=true
  coldStorage=true

[governance]
  type="Decentralized"
  votingMechanism="Proof of Stake (PoS)"

[contact]
  email="info@alnitaknet.online"
  website="https://www.alnitaknet.online"

[[PRINCIPALS]]
name="Orion Group"
email="info@alnitaknet.online"

  




