# General Information
ACCOUNTS = ["GCKSI3G65TXQ7KMSEQY4FUHQONZ5YLJIVI5VUYHSV4ILHNQHQSC325UA", "GAJUZ3LR4DLJAUQPZT2MKPUOHVEYH6QZRYZOQXNP3R2VRXUD53PVUVCK"] #
# NETWORK_PASSPHRASE ="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Alnitak"
ORG_URL="https://www.alnitaknet.online"
ORG_DESCRIPTION="Alnitak is a non Anchor-Based utility token on the Stellar Blockchain. It is permanently Capped at 100,000,000 total Supply"
ORG_OFFICIAL_EMAIL="official@alnitaknet.online"
ORG_SUPPORT_EMAIL="support@alnitaknet.online"
ORG_LOCATION="Cal, Nigeria"
ORG_LOGO="https://github.com/btgod443-dev/alnitak/blob/main/.assets/logo.png"


[[CURRENCIES]]
code="xALT"
issuer="GCKSI3G65TXQ7KMSEQY4FUHQONZ5YLJIVI5VUYHSV4ILHNQHQSC325UA"
status = "live"
display_decimals="7"
is_asset_anchored=false
desc="Alnitak is a utility token on Stellar"
image="https://github.com/btgod443-dev/alnitak/blob/main/.assets/logo.png"

[[PRINCIPALS]]
name="Orion Group"
email="info@alnitaknet.online"










