# General Information

[[PRINCIPALS]]
org_name = "Orion Group"
org_url = "https://orbxorion.online/orion-group"
org_desc = "Orion Group develops utility-focused blockchain solutions on Stellar, with ORBX serving as the core token for staking, rewards, payments, and ecosystem participation."
org_official_email = "official@orbxorion.online"
org_support_email = "support@orbxorion.online"
org_physical_address = "Cal, Nigeria"
name = "EMINENCE"
github = "https://github.com/OrbitORBX-dev"
twitter = "@orbxorion"


[[CURRENCIES]]
name = "OrbitX"
code = "ORBX"
issuer = "GDYTQGDGHRXOIWANOUB4DY6BTKMMWTF5PVJC2KZVT6VFP5TYD7W63XO7"
status = "live"
display_decimals = 7
is_asset_anchored = false
fixed_number = 100000000
desc = "Orbit ORBX is a non Anchor-Based Orion Group utility token on the Stellar Blockchain."
image = "https://orbxorion.online/assets/logo.png"
