# General Information
ACCOUNTS = ["GCKSI3G65TXQ7KMSEQY4FUHQONZ5YLJIVI5VUYHSV4ILHNQHQSC325UA", "GAJUZ3LR4DLJAUQPZT2MKPUOHVEYH6QZRYZOQXNP3R2VRXUD53PVUVCK"] #
# NETWORK_PASSPHRASE ="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Alnitaknet"
ORG_URL="https://www.alnitaknet.online"
ORG_LOGO="https://drive.google.com/file/d/1HoPD7ovBOKFZ_WvFi89lT1LqXtIMNIyK/view?usp=sharing"
ORG_PHYSICAL_ADDRESS="Calabar,Nigeria"
ORG_OFFICIAL_EMAIL="official@alnitaknet.online"
ORG_SUPPORT_EMAIL="support@alnitaknet.online"
ORG_DESCRIPTION="Alnitak is a non Anchor-Based utility token on Stellar"

[[PRINCIPALS]]
name="Orion Group"
email="orion@alnitaknet.online"

[[CURRENCIES]]
code="xALT"
issuer="GCKSI3G65TXQ7KMSEQY4FUHQONZ5YLJIVI5VUYHSV4ILHNQHQSC325UA"
is_asset_anchored=false
desc="Alnitak is a utility token on Stellar"
image="https://drive.google.com/file/d/1HoPD7ovBOKFZ_WvFi89lT1LqXtIMNIyK/view?usp=sharing"




