# General Information
ACCOUNTS = ["GCQD5F4QP3AZIBJAIK5LZGCY3TCA65KG3XUF25WQ2BVFVRKLX7277J57","GA67JGLPHZ2S3I2HIFIDNFEB65XS4WNTDCLDABTD4BHBQEXLL3MODDXS"] #
# NETWORK_PASSPHRASE ="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Orbit"
ORG_URL="https://www.orbitx.online"
ORG_DESCRIPTION="Orbit ORBX is a non Anchor-Based utility token on the Stellar Blockchain. It is permanently Capped at 100,000,000 total Supply"
ORG_OFFICIAL_EMAIL="official@orbitx.online"
ORG_SUPPORT_EMAIL="support@orbitx.online"
ORG_PHYSICAL_ADDRESS="Cal, Nigeria"
ORG_LOGO="https://orbitx.online/assets/orbx-logo.png"


[[CURRENCIES]]
code="ORBX"
issuer="GCQD5F4QP3AZIBJAIK5LZGCY3TCA65KG3XUF25WQ2BVFVRKLX7277J57"
status = "live"
display_decimals="7"
is_asset_anchored=false
desc="Orbit is a utility token on Stellar"
image="https://orbitx.online/assets/orbx-logo.png"

[[PRINCIPALS]]
name="EMINENCE"








